apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    name: hello-world
spec:
  entrypoint: alpine
  templates:
  - name: alpine
    container:
      image: alpine:3.11.6
      command: [echo]
      args: ["hello world"]
